name: cooking_assist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  loading_animation_widget: ^1.3.0
  get: ^4.7.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/cooking_assistant_logo.svg

  fonts:
    - family: Caveat
      fonts:
        - asset: lib/assets/fonts/Caveat-Regular.ttf
        - asset: lib/assets/fonts/Caveat-Bold.ttf
          weight: 700